In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings


# filter out warning messages
warnings.filterwarnings("ignore")

In [16]:
books=pd.read_csv(r"D:\DATASET\book recommendation\Books.csv")
users=pd.read_csv(r"D:\DATASET\book recommendation\Users.csv")
rating=pd.read_csv(r"D:\DATASET\book recommendation\Ratings.csv")

In [17]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [18]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [19]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [20]:
print(rating.shape)
print(users.shape)
print(books.shape)

(1149780, 3)
(278858, 3)
(271360, 8)

In [21]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [22]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [23]:
rating.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

# Duplicated

In [24]:
books.duplicated().sum()

0

In [25]:
rating.duplicated().sum()

0

In [26]:
users.duplicated().sum()

0

# EDA

In [27]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [28]:
books.groupby("Year-Of-Publication").count()

,ISBN,Book-Title,Book-Author,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Year-Of-Publication,,,,,,,
0,3570,3570,3570,3570,3570,3570,3570
1806,1,1,1,1,1,1,1
1900,1,1,1,1,1,1,1
1901,7,7,7,7,7,7,7
1902,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...
2024,1,1,1,1,1,1,1
2030,3,3,3,3,3,3,3
2037,1,1,1,1,1,1,1
DK Publishing Inc,2,2,2,2,2,2,0
Gallimard,1,1,1,1,1,1,0

In [29]:
books[books['Year-Of-Publication']==0].shape[0]

3570

In [30]:
# there are 3570 rows , where year of publication is 0 -- means year is not mention

In [31]:
books[books['Year-Of-Publication']=='2037']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
255409,068471809X,To Have and Have Not,Ernest Hemingway,2037,Simon &amp; Schuster,http://images.amazon.com/images/P/068471809X.0...,http://images.amazon.com/images/P/068471809X.0...,http://images.amazon.com/images/P/068471809X.0...

In [32]:
# to have and have not book is 1937 book not 2037
books["Year-Of-Publication"].replace("2037","1937",inplace=True)

In [33]:
books[books['Year-Of-Publication']=='DK Publishing Inc']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
209538,078946697X,"DK Readers: Creating the X-Men, How It All Beg...",2000,DK Publishing Inc,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,NaN
221678,0789466953,"DK Readers: Creating the X-Men, How Comic Book...",2000,DK Publishing Inc,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,NaN

In [34]:
books[books['Year-Of-Publication']=='DK Publishing Inc'].shape[0]

2

In [35]:
books["Year-Of-Publication"].replace("DK Publishing Inc","2000",inplace=True)

In [36]:
books[books['Book-Author']=='2000']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
209538,078946697X,"DK Readers: Creating the X-Men, How It All Beg...",2000,2000,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,NaN
221678,0789466953,"DK Readers: Creating the X-Men, How Comic Book...",2000,2000,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,NaN

In [37]:
books["Book-Author"].replace("2000","DK Publishing Inc",inplace=True)

In [38]:
# in dataset there are in some some rows ,  instead of year_of_publication , book_author is given and vice versa

In [39]:
books[books['Year-Of-Publication']=='Gallimard']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
220731,2070426769,"Peuple du ciel, suivi de 'Les Bergers\"";Jean-M...",2003,Gallimard,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,NaN

In [40]:
books["Year-Of-Publication"].replace("Gallimard","2003",inplace=True)

In [41]:
books[books['Book-Author']=='2003']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
220731,2070426769,"Peuple du ciel, suivi de 'Les Bergers\"";Jean-M...",2003,2003,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,NaN

In [42]:
books["Book-Author"].replace("2003","Gallimard",inplace=True)
# in dataset there are in some some rows ,  instead of year_of_publication , book_author is given and vice versa

In [43]:
books.groupby("Year-Of-Publication").count()

,ISBN,Book-Title,Book-Author,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Year-Of-Publication,,,,,,,
0,3570,3570,3570,3570,3570,3570,3570
1806,1,1,1,1,1,1,1
1900,1,1,1,1,1,1,1
1901,7,7,7,7,7,7,7
1902,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...
2011,1,1,1,1,1,1,1
2012,1,1,1,1,1,1,1
2020,1,1,1,1,1,1,1
2024,1,1,1,1,1,1,1
2030,3,3,3,3,3,3,3

In [44]:
books[books['Year-Of-Publication']=='2030']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
228173,0671266500,FOREST PEOPLE (Touchstone Books (Hardcover)),Colin M. Turnbull,2030,Simon &amp; Schuster,http://images.amazon.com/images/P/0671266500.0...,http://images.amazon.com/images/P/0671266500.0...,http://images.amazon.com/images/P/0671266500.0...
240169,0684718022,In Our Time: Stories (Scribner Classic),Ernest Hemingway,2030,Collier Books,http://images.amazon.com/images/P/0684718022.0...,http://images.amazon.com/images/P/0684718022.0...,http://images.amazon.com/images/P/0684718022.0...
260974,0671740989,FOOTBALL SUPER TEAMS : FOOTBALL SUPER TEAMS,Bill Gutman,2030,Simon &amp; Schuster Children's Publishing,http://images.amazon.com/images/P/0671740989.0...,http://images.amazon.com/images/P/0671740989.0...,http://images.amazon.com/images/P/0671740989.0...

In [45]:
books["Year-Of-Publication"].replace("2030","1961",inplace=True)

In [46]:
books.groupby("Year-Of-Publication").count()

,ISBN,Book-Title,Book-Author,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Year-Of-Publication,,,,,,,
0,3570,3570,3570,3570,3570,3570,3570
1806,1,1,1,1,1,1,1
1900,1,1,1,1,1,1,1
1901,7,7,7,7,7,7,7
1902,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...
2008,1,1,1,1,1,1,1
2011,1,1,1,1,1,1,1
2012,1,1,1,1,1,1,1
2020,1,1,1,1,1,1,1
2024,1,1,1,1,1,1,1

In [47]:
books[books['Year-Of-Publication']=='2024']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
246842,0380000059,CLOUT,D. GIBBONS,2024,Avon,http://images.amazon.com/images/P/0380000059.0...,http://images.amazon.com/images/P/0380000059.0...,http://images.amazon.com/images/P/0380000059.0...

In [48]:
books["Year-Of-Publication"].replace("2024","2013",inplace=True)

# complete the EDA part

# Build up popularity based recommendation system

In [49]:
rating_with_name=rating.merge(books,on='ISBN')

In [50]:
rating_with_name.sample()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
441632,102189,0451171128,8,Cat on a Hot Tin Roof,Tennessee Williams,1989,Signet Book,http://images.amazon.com/images/P/0451171128.0...,http://images.amazon.com/images/P/0451171128.0...,http://images.amazon.com/images/P/0451171128.0...

In [51]:
rating_with_name.shape

(1031136, 10)

In [52]:
num_rating_df=rating_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [53]:
num_rating_df.rename(columns={'Book-Rating':'num-rating'},inplace=True)
num_rating_df

                                               Book-Title  num-rating
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.           2
241067                     Ã?Â?rger mit Produkt X. Roman.           4
241068                                Ã?Â?sterlich leben.           1
241069                              Ã?Â?stlich der Berge.           3
241070                                  Ã?Â?thique en toc           2

[241071 rows x 2 columns]

In [54]:
avg_rating_df=rating_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg-rating'},inplace=True)
avg_rating_df

                                               Book-Title  avg-rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [55]:
popularity_df=num_rating_df.merge(avg_rating_df,on='Book-Title')

In [56]:
popularity_df

,Book-Title,num-rating,avg-rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [57]:
popular_book=popularity_df[popularity_df['num-rating']>300].sort_values('avg-rating',ascending=False).head(50)

In [58]:
popular_book

,Book-Title,num-rating,avg-rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
206502,The Secret Life of Bees,774,4.447028
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
170101,Suzanne's Diary for Nicholas,457,3.820569
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,3.766871
118237,Me Talk Pretty One Day,457,3.752735
219349,Timeline,552,3.750000
14392,Angels &amp; Demons,670,3.708955
21754,Bel Canto: A Novel,350,3.702857
230246,Watership Down,312,3.698718
38814,Confessions of a Shopaholic (Summer Display Op...,350,3.634286
60166,Empire Falls,392,3.630102
112932,Lucky : A Memoir,301,3.621262
202550,The Poisonwood Bible: A Novel,494,3.609312
148038,Red Dragon,402,3.606965
202244,The Pilot's Wife : A Novel,568,3.593310
818,1st to Die: A Novel,509,3.575639
159301,She's Come Undone (Oprah's Book Club),468,3.570513
200253,The Notebook,650,3.560000
93210,Interview with the Vampire,508,3.551181
199237,The Nanny Diaries: A Novel,828,3.530193
27922,Bridget Jones's Diary,815,3.527607
233850,White Oleander : A Novel,387,3.506460

In [59]:
popular_book.merge(books,on='Book-Title').drop_duplicates('Book-Title')

,Book-Title,num-rating,avg-rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,043935806X,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
9,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...
12,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370,0345339703,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...
21,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652,059035342X,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...
23,To Kill a Mockingbird,510,4.700000,0446310786,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
31,The Da Vinci Code,898,4.642539,0385504209,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...
37,The Five People You Meet in Heaven,430,4.551163,0786868716,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...
39,The Catcher in the Rye,449,4.545657,0316769487,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...
46,The Lovely Bones: A Novel,1295,4.468726,0316666343,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...
47,The Secret Life of Bees,774,4.447028,0142001740,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...
53,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,0385484518,MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...
56,The Red Tent (Bestselling Backlist),723,4.334716,0312195516,Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...
57,Nickel and Dimed: On (Not) Getting By in America,335,4.289552,0805063897,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...
59,Fahrenheit 451,409,4.264059,3257208626,Ray Bradbury,1994,Distribooks Inc,http://images.amazon.com/images/P/3257208626.0...,http://images.amazon.com/images/P/3257208626.0...,http://images.amazon.com/images/P/3257208626.0...
72,Girl with a Pearl Earring,526,4.218631,0452282152,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...,http://images.amazon.com/images/P/0452282152.0...,http://images.amazon.com/images/P/0452282152.0...
73,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983,0446672211,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...,http://images.amazon.com/images/P/0446672211.0...,http://images.amazon.com/images/P/0446672211.0...
74,Life of Pi,664,4.088855,0151008116,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...,http://images.amazon.com/images/P/0151008116.0...,http://images.amazon.com/images/P/0151008116.0...
78,The Bean Trees,389,4.087404,0060915544,Barbara Kingsolver,1989,Perennial,http://images.amazon.com/images/P/0060915544.0...,http://images.amazon.com/images/P/0060915544.0...,http://images.amazon.com/images/P/0060915544.0...
81,Good in Bed,490,4.055102,0743418174,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...,http://images.amazon.com/images/P/0743418174.0...,http://images.amazon.com/images/P/0743418174.0...
83,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383,0060938455,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...,http://images.amazon.com/images/P/0060938455.0...,http://images.amazon.com/images/P/0060938455.0...
84,American Gods,302,4.006623,0380789035,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...,http://images.amazon.com/images/P/0380789035.0...,http://images.amazon.com/images/P/0380789035.0...
85,Skipping Christmas,322,4.006211,0385505833,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...,http://images.amazon.com/images/P/0385505833.0...,http://images.amazon.com/images/P/0385505833.0...
91,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145,0842329129,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...,http://images.amazon.com/images/P/0842329129.0...,http://images.amazon.com/images/P/0842329129.0...
93,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000,037582345X,PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...
101,The Color Purple,314,3.964968,0671617028,Alice Walker,1985,Pocket Books,http://images.amazon.com/images/P/0671617028.0...,http://images.amazon.com/images/P/0671617028.0...,http://images.amazon.com/images/P/0671617028.0...
107,Suzanne's Diary for Nicholas,457,3.820569,0316969443,James Patterson,2001,"Little, Brown",http://images.amazon.com/images/P/0316969443.0...,http://images.amazon.com/images/P/0316969443.0...,http://images.amazon.com/images/P/0316969443.0...
111,A Prayer for Owen Meany,413,3.796610,0345361792,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...
113,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409,0345313860,ANNE RICE,1986,Ballantine Books,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...
114,White Oleander : A Novel (Oprah's Book Club),356,3.772472,0316284955,Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...
115,Wicked: The Life and Times of the Wicked Witch...,326,3.766871,0060987103,Gregory Maguire,1996,Regan Books,http://images.amazon.com/images/P/0060987103.0...,http://images.amazon.com/images/P/0060987103.0...,http://images.amazon.com/images/P/0060987103.0...
116,Me Talk Pretty One Day,457,3.752735,0316776963,David Sedaris,2001,Back Bay Books,http://images.amazon.com/images/P/0316776963.0...,http://images.amazon.com/images/P/0316776963.0...,http://images.amazon.com/images/P/0316776963.0...
120,Timeline,552,3.750000,0345417623,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...
127,Angels &amp; Demons,670,3.708955,0671027360,Dan Brown,2001,Pocket Star,http://images.amazon.com/images/P/0671027360.0...,http://images.amazon.com/images/P/0671027360.0...,http://images.amazon.com/images/P/0671027360.0...
132,Bel Canto: A Novel,350,3.702857,0060934417,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
133,Watership Down,312,3.698718,038039586X,Richard George Adams,1975,Harpercollins,http://images.amazon.com/images/P/038039586X.0...,http://images.amazon.com/images/P/038039586X.0...,http://images.amazon.com/images/P/038039586X.0...
137,Confessions of a Shopaholic (Summer Display Op...,350,3.634286,0385335482,SOPHIE KINSELLA,2001,Delta,http://images.amazon.com/images/P/0385335482.0...,http://images.amazon.com/images/P/0385335482.0...,http://images.amazon.com/images/P/0385335482.0...
138,Empire Falls,392,3.630102,0375726403,Richard Russo,2002,Vintage Books USA,http://images.amazon.com/images/P/0375726403.0...,http://images.amazon.com/images/P/0375726403.0...,http://images.amazon.com/images/P/0375726403.0...
141,Lucky : A Memoir,301,3.621262,0316096199,Alice Sebold,2002,Back Bay Books,http://images.amazon.com/images/P/0316096199.0...,http://images.amazon.com/images/P/0316096199.0...,http://images.amazon.com/images/P/0316096199.0...
142,The Poisonwood Bible: A Novel,494,3.609312,0060930535,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
143,Red Dragon,402,3.606965,0440206154,Thomas Harris,2000,Dell Publishing Company,http://images.amazon.com/images/P/0440206154.0...,http://images.amazon.com/images/P/0440206154.0...,http://images.amazon.com/images/P/0440206154.0...
151,The Pilot's Wife : A Novel,568,3.593310,0316601950,Anita Shreve,1999,Back Bay Books,http://images.amazon.com/images/P/0316601950.0...,http://images.amazon.com/images/P/0316601950.0...,http://images.amazon.com/images/P/0316601950.0...
152,1st to Die: A Novel,509,3.575639,0446610038,James Patterson,2002,Warner Vision,http://images.amazon.com/images/P/0446610038.0...,http://images.amazon.com/images/P/0446610038.0...,http://images.amazon.com/images/P/0446610038.0...
154,She's Come Undone (Oprah's Book Club),468,3.570513,0671021001,Wally Lamb,1998,Pocket,http://images.amazon.com/images/P/0671021001.0...,http://images.amazon.com/images/P/0671021001.0...,http://images.amazon.com/images/P/0671021001.0...
155,The Notebook,650,3.560000,0446605239,Nicholas Sparks,1998,Warner Books,http://images.amazon.com/images/P/0446605239.0...,http://images.amazon.com/images/P/0446605239.0...,http://images.amazon.com/images/P/0446605239.0...
160,Interview with the Vampire,508,3.551181,0345337662,Anne Rice,1993,Ballantine Books,http://images.amazon.com/images/P/0345337662.0...,http://images.amazon.com/images/P/0345337662.0...,http://images.amazon.com/images/P/0345337662.0...
162,The Nanny Diaries: A Novel,828,3.530193,0312278586,Emma McLaughlin,2002,St. Martin's Press,http://images.amazon.com/images/P/0312278586.0...,http://images.amazon.com/images/P/0312278586.0...,http://images.amazon.com/images/P/0312278586.0...
164,Bridget Jones's Diary,815,3.527607,0330332775,Helen Fielding,1997,Picador (UK),http://images.amazon.com/images/P/0330332775.0...,http://images.amazon.com/images/P/0330332775.0...,http://images.amazon.com/images/P/0330332775.0...
170,White Oleander : A Novel,387,3.506460,0316182540,Janet Fitch,2001,"Little, Brown",http://images.amazon.com/images/P/0316182540.0...,http://images.amazon.com/images/P/0316182540.0...,http://images.amazon.com/images/P/0316182540.0...

In [60]:
popular_book=popular_book.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num-rating','avg-rating']]

In [61]:
popular_book

# top 50 book based on avg rating where avg rating calculated on votes more than 250

,Book-Title,Book-Author,Image-URL-M,num-rating,avg-rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
9,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
12,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
21,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
23,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
31,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
37,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
39,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
46,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
47,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
53,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
56,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
57,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
59,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
72,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
73,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
74,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
78,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
81,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
83,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
84,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
85,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
91,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
93,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
101,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
107,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
111,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
113,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
114,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472
115,Wicked: The Life and Times of the Wicked Witch...,Gregory Maguire,http://images.amazon.com/images/P/0060987103.0...,326,3.766871
116,Me Talk Pretty One Day,David Sedaris,http://images.amazon.com/images/P/0316776963.0...,457,3.752735
120,Timeline,MICHAEL CRICHTON,http://images.amazon.com/images/P/0345417623.0...,552,3.750000
127,Angels &amp; Demons,Dan Brown,http://images.amazon.com/images/P/0671027360.0...,670,3.708955
132,Bel Canto: A Novel,Ann Patchett,http://images.amazon.com/images/P/0060934417.0...,350,3.702857
133,Watership Down,Richard George Adams,http://images.amazon.com/images/P/038039586X.0...,312,3.698718
137,Confessions of a Shopaholic (Summer Display Op...,SOPHIE KINSELLA,http://images.amazon.com/images/P/0385335482.0...,350,3.634286
138,Empire Falls,Richard Russo,http://images.amazon.com/images/P/0375726403.0...,392,3.630102
141,Lucky : A Memoir,Alice Sebold,http://images.amazon.com/images/P/0316096199.0...,301,3.621262
142,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,494,3.609312
143,Red Dragon,Thomas Harris,http://images.amazon.com/images/P/0440206154.0...,402,3.606965
151,The Pilot's Wife : A Novel,Anita Shreve,http://images.amazon.com/images/P/0316601950.0...,568,3.593310
152,1st to Die: A Novel,James Patterson,http://images.amazon.com/images/P/0446610038.0...,509,3.575639
154,She's Come Undone (Oprah's Book Club),Wally Lamb,http://images.amazon.com/images/P/0671021001.0...,468,3.570513
155,The Notebook,Nicholas Sparks,http://images.amazon.com/images/P/0446605239.0...,650,3.560000
160,Interview with the Vampire,Anne Rice,http://images.amazon.com/images/P/0345337662.0...,508,3.551181
162,The Nanny Diaries: A Novel,Emma McLaughlin,http://images.amazon.com/images/P/0312278586.0...,828,3.530193
164,Bridget Jones's Diary,Helen Fielding,http://images.amazon.com/images/P/0330332775.0...,815,3.527607
170,White Oleander : A Novel,Janet Fitch,http://images.amazon.com/images/P/0316182540.0...,387,3.506460

# Recommendation Engine With Collaborative Filtering